name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name:  Download videos from Witty.tv
        uses: actions/setup-node@v3
        with:
          node-version: '18.9.1'
      - name: Install dependencies
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth axios
      - name: Download choco
        run: powershell -c "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
      - name: Install ffmpeg
        run: choco install ffmpeg sed -y
      - name:  Run
        run: .\get_video.cmd ${{ vars.VIDEO_URL }}
      - name: Extract video name
        id: extract
        run: |
          video_title=$(echo $VIDEO_URL | grep -oP '(?<=/)[^/]+$')
      - name: Set output
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'
        id: setup-go
      - name: Run the script
        run: |
          echo "Video title: ${{ steps.extract_title.outputs.video_title }}"
      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.extract_title.outputs.video_title }}
          path: ./*PART00*
      - name: Download video  
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.extract_title.outputs.video_title }}
      - name: Download Init
        run: dir



