name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Estrai nome puntata
        run: |
          video_url="${{ env.VIDEO_URL }}"
          name_puntata=$(echo "$video_url" | sed -E 's#.*/(.*)-.*#\1#')
          echo "name_puntata=$name_puntata" >> $GITHUB_ENV
      - name: Stampa nome puntata
        run: echo ${{name_puntata}}
      - name:  Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18.9.1'
      - name: Install dependencies
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth axios
      - name: Download choco
        run: powershell -c "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
      - name: Install ffmpeg
        run: choco install ffmpeg sed -y
      - name:  Run
        run: .\get_video.cmd ${{ vars.VIDEO_URL }}
      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: ./*PART00*
      - name: Download video  
        uses: actions/download-artifact@v4
        with:
          name: videos
      - name: Download Init
        run: dir



