name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name:  Download videos from Witty.tv
        uses: actions/setup-node@v3
        with:
          node-version: '18.9.1'
      - name: Install dependencies
        run: npm install puppeteer-extra puppeteer-extra-plugin-stealth puppeteer-core axios
      - name: Download choco
        run: powershell -c "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
      - name: Install ffmpeg
        run: choco install ffmpeg -y
      - name:  Run
        run: .\get_video.cmd ${{ vars.VIDEO_URL }}
