name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name:  Download videos from Witty.tv
        uses: actions/setup-node@v3
        with:
          node-version: '18.9.1'
      - name: Install dependencies
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth axios
      - name: Download choco
        run: powershell -c "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
      - name: Install ffmpeg
        run: choco install ffmpeg -y
      - name:  Run
        run: .\get_video.cmd ${{ vars.VIDEO_URL }}
      - name: Extract video title
        run: ffprobe -v quiet -print_format json -show_format -show_streams input.mp4 > metadata.json
      - name: Set title variable
        run: title=$(jq -r '.format.tags.title' metadata.json)
      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ title }}
          path: ./*PART00*
      - name: Download video  
        uses: actions/download-artifact@v4
        with:
          name: ${{ title }}
      - name: Download Init
        run: dir



